kakao:
  REST_API_KEY: 0ca067b0f5f2165d0b8d1de680b15bb2

naver:
  REST_API_KEY_ID: qbr5wrlgt0
  REST_API_KEY: 96dyEo4k9HyrQve4o1JuRQuWiui3Zri1MtyMKZA2

jwt:
  key:
    secret: findToilet_jwt_key_secret_finebears_janghankyu
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 3600

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0ca067b0f5f2165d0b8d1de680b15bb2
            client-secret: eEf2FDApIvA5eFcQOh9h4jP0RfaPTbkr
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
